services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
      - .env.test
    networks:
      - pytestnetwork
    ports:
      - "8000:8000"

networks:
  pytestnetwork:
